server:
  port: 8086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  elasticsearch:
    rest:
      uris: http://192.168.0.108:9200
  jackson:
    default-property-inclusion: non_null
feign:
  client:
    config:
      default:
        connectTimeout: 300000
        readTimeout: 300000
ribbon:
  ReadTimeout: 300000
  ConnectTimeout: 300000
