server:
  port: 8888
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: pms-route
          uri: lb://pms-service
          predicates:
            - Path=/pms/**
        - id: sms-route
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: ums-route
          uri: lb://ums-service
          predicates:
            - Path=/ums/**
        - id: oms-route
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: wms-route
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
    nacos:
      discovery:
        server-addr: localhost:8848
