server:
  port: 8083
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.1.1.0:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_wms
    username: root
    password: 1234
  redis:
    host: localhost
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/wms/**/*.xml